version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 80s
    networks:
      - node-network
    volumes:
      - /usr/src/app
    ports:
      -"3000:3000"
    restart: always
    tty: true
    depends_on:
      - nginx
      - db

    db:
      image: mysql:5.7
      container_name: db
      restart: always
      tty: true
      volumes:
        - ./mysql:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      -"8080:80"
    depends_on:
      - app